language: csharp
mono: none
dist: trusty
dotnet: 2.0.0
script:
- dotnet build -c Release
- dotnet pack -c Release
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push src/MockServerClientNet/bin/Release/MockServerClientNet.*.nupkg --api-key $NUGET_API_KEY
  on:
    tags: true
env:
  global:
  - secure: U4X+rMMK/b4f1HQ2cjaw00E3FUf/PgUGCtRsLNgnv+zmnIcz0s+p7t15s9+EI4nWDINLqUqElc7xiLuawB2Hc6JKjLj1jnzxP+JqZ2kEfG1B3DwgkBc+Id/ElN/1smiPYMrz/fp1Y3e1wdxxGgGc9yIHhT6aOpIOFBN9d1ujmdY7ss5qrMy9vPSwpP4FA9FJtDbHhN+9iiQeA7zGhc7AOpfLW9poJ8HoPAIDhIQfNInsnZVuZ9aZIRNPjOjUx6rHm7OzDLZ0ZpABspw6HDSsPm1k6eVJbvpg3jX8kMF+f10ibE1Z1d2+hUt43YiVJjEllPXXjuxOjqgR3xXkLzpD1h8DTOxz+Xfd0yrkEUHPkFLgfmeDkGY5jD2P6h1A7xUuko8ODRD8SD+EHUM3+GGD8zv3jm/mmcJk6EKOzox269DNj1iG2hzzWHDNlmfzATuCCyjOBNSTAVsm3wQM0cgtgfnvCijff+z25Jlubtj4kVVCoPjkkYEIHfgy1HOpLdMGnPCb9XlcFmdVA994z7fB2I/ZvZ9wKa8fwtobRID2ZeV/u7SxOg3LbEMZ3ziWVXbbH0i7HPFY6OiHACCZhFREyNvvkUYl6APV4CNpGZgz3uLYjNknWyWLijECYvM1hATCRaZ3mZH4e/IiqZyQ5wjQhmfSaXdPK4S6pDZLoSIF+kw=
