language: csharp
mono: none
dist: trusty
dotnet: 2.0.0
script:
- dotnet build -c Release
- dotnet pack -c Release
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push src/MockServerClientNet/bin/Release/MockServerClientNet.*.nupkg --api-key $NUGET_API_KEY
  on:
    tags: true
env:
  global:
  - secure: sCnPy6erLf4irANhmikooZmjeHosbfFcqjqUKF3RGj75w/KdVNwldKkVDFc1Ly5xQHjdhcbKCqPR+/N/5wmZSKRFrYIdzGGb5/Sv55BPDyIBgPa20dkTuxfF8bk+m6gmskeEN6XJphUc0b+tayH+B8KUKKnLe6KzhfIJblgJiT+KUWaVc+uuBsX7RhgNhkdLQQal2V5wZ0f3TqfNllsttg90zcmPFtglyNajpcIzIxI7fZiIcYf7lj18hBNmJs2wnQihOd3ATgnM0jn+rshrgt6D+QYSuZ3Hn3aqTjMDyUcwPmlRwVDCsxx37dzsZoDV2+BXSMF91OWVLar716Y0qgNbVMaUtc8XaFQ8agdS5uTcg2uJVL7heZGwQrUUdJoX2Ii/MswABUS4tdonBB2+td4BcVNZ5aeoOnrn+Fl0+Kn/PF8nmOohe+y42pzF0PmBumJRP2XFz9zUwEM76GfO2PFA+Q6u6pYgM51rJ0vDW6qZFpWYRju8GqeGB5ot/62zVLO0EA5bD/eB3BL3GCepA/OF3pfT3z9GwaMJvSK3V5O80CT2j92U4C6LU8tIPnQ4X5L2wGuTKCk8hVAW9t1y3uTswWJ879VkGQE2q9cC6v11gfkFEm/bnbvNznjIkwzQb2PTaKvrAJtjz2Ae9mvNAK1/IC5tJzyJSHOFIa29QTQ=
