language: csharp
mono: none
dist: trusty
dotnet: 2.0.0
script:
- dotnet build -c Release
- dotnet pack -c Release
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push src/MockServerClientCSharp/bin/Release/MockServerClientCSharp.*.nupkg --api-key $NUGET_API_KEY
  on:
    tags: true
env:
  global:
    secure: hxppyU7MIxIpLRBXiC2aiPsbI9rQzZV+V+n7JHb3tvcaXeM/cAMB3Bjed0QT/bKC7V9c5Sg75obN1anYbXAwf+lVgfYH7k1SMrnSq+CeoTNd6GhKaaJ7nYgaFTFgro6c8ko9GMrIO3PLg5vGmVfnrAunf+tW9UMxBin/A38opeIbvihwjzqiE8kElABUc4EOJAyqxsXPNjMwkjzAqes8CUW3u+gqpXA8LOzvUq0z9rhI9lGFWSoh0HxByqvTDgAshl4j3qAPCQosJXuKM2JRngdhwLDszoNdSFfsyka1CuwjivR4k/E/ZhVcb0pX5IjbecOjc32qdsi/219/OwHfrxZp6Q6YEU8ckwC8AY3tyYw1emUg1x4mVer8U91fAltSemaUpaQ4D9ndPtocnr1J1Hv5/LSgO2DpM9c22GRIUFtOaZqS6X9cMPoO6e/dqOtkeDGpOm5vRae7Ks4xNJCb7GEUjfFfM5ZYhSvAFzDMjxwxhjqN8gyJStNg1kubeGYVOXt3iibB4B5+v0FjXUBifHWVOz0bL/ud6B46JSLiVGMnqNSXft2jOHL5lEWLxZ9yS4FEhl/vp6bwn1GDDEm0QKYn/xBS2regzK5LaB4xKCUeYHUaHcVFhVmSU029m0cZ3e172q0Mt8OiAT/zRW5ZmxfNdpJmwAMBA+i5XpbGR+M=
