version: "3.8"
services:
  mockserver-proxy1080:
    image: mockgds.azurecr.io/mockserver:5.11.1
    ports:
      - 1080:1080
    environment:
      LOG_LEVEL: "INFO"
      SERVER_PORT: 1080
    container_name: mockserver-proxy1080
  mockserver-instance4080:
    image: mockgds.azurecr.io/mockserver:5.11.1
    ports:
      - 4080:4080
    environment:
      LOG_LEVEL: "INFO"
      SERVER_PORT: 4080
    container_name: mockserver-instance4080
  mockserver-instance4081:
    image: mockgds.azurecr.io/mockserver:5.11.1
    ports:
      - 4081:4081
    environment:
      LOG_LEVEL: "WARN"
      SERVER_PORT: 4081
    container_name: mockserver-instance4081
  mockserver-instance4082:
    image: mockgds.azurecr.io/mockserver:5.11.1
    ports:
      - 4082:4082
    environment:
      LOG_LEVEL: "WARN"
      SERVER_PORT: 4082
    container_name: mockserver-instance4082
networks:
  default:
    name: mockserver_default
